import Head from 'next/head'
import HomePage from '../Containers/HomePage'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Jenny Dnh Portfolio 2021</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </div>
  )
}
